### ISSUE TITLE
[BUG] Weird driving characteristics - Add cars with this issue here

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#1635]
### Your Discord Name

SwickMachine#6355

### A clear and concise description of what the bug is

Some cars are driving oddly. You turn the wheel and it presses the accelerator at the same time. 

Buffalo STX and Bravado Vulture are two doing it now. 

### Steps to Reproduce the Bug

Get in car.

Try to drive forward and turn. 

Cant stop. 

### Expected Behavior

Drive normally. 

### Screenshots/Videos

N/A

**Comment by M1ngh** [comment]
ENUS is also doing that, lost speed and if you go left and right he goes backards and dont turn

**Comment by JnKTechstuff** [comment]
keep adding cars and ill look soon

**Comment by SwickMachine** [comment]
Granger XL

**Comment by BlazinNut** [comment]
ISSI 4X4 CLASSIC: Try turning and it just spins out really easy, also maybe slow it down a bit

**Comment by BlazinNut** [comment]
10F WideBody will only hit 125 on straights

**Comment by tusktheshrew** [comment]
Buffalo STX

**Comment by Drunkle716** [comment]
> Granger XL

3600

**Comment by LitrlyD3ad** [comment]
Both the Hotring Saber and the Hotring Paradox are both performing off from what they was before, not sure if it was intentional or not but it happened right when the rest of these cars went weird too, the Paradox would wheelspin at low speeds and it went up to a higher speed than it does now, And now the Paradox has a chance to go zero gravity? it kinda floats if i hit something hard, im not sure how to describe it really but it only happened to me a few times and im not sure how to replicate it.
