### ISSUE TITLE
[BUG] Legion crash due to SADOT lights

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#1662]
### Your Discord Name

SketchyNath

### A clear and concise description of what the bug is

Removing SADOT temporary traffic light at the west side of Legion Square. Made us all crash and people that drive through have the same issue. Cannot get back into server due to crashing

### Steps to Reproduce the Bug

1. place temporary light
2. remove temporary light
3. Game crash
4. try to reload to same area

### Expected Behavior

I expect to use the temporary lights without crashing i guess

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1mu3u821NQrl8A/d1337WzSuUQE?invite=cr-MSxWUm4sMTk0ODMwMjk0LA

**Comment by CorFinn** [comment]
Here is the series of events that led to this. I'm thinking that since I was the one to create the prop, moving beyond its range may have borked it.

1. Placed all scene items, then light and stop zone, then changed light to red.
2. Continued my scene, experiencing some issues with the Downed Tree event.
3. A player drove thru my scene, tried to sell me Class 2's, steal my car, then VDM'd me.
4. I was taken to the hospital, moving me well away from my spawned prop.
5. After the hospital visit, I arrived back to my scene. The lights on the traffic light are not displaying at this point. (They showed up fine before I left the area.)
6. Attempted to remove the light with F1 menu. Upon initial F1 press, game crashes. I didn't go into the F1 Tow Menu, just the basic one.
7. Attempting to log back into Last Location crashes game repeatedly.

**Comment by SketchyNath** [comment]
I did notice the light was not displaying any color when I arrived on the scene which is before you were taken to the hospital.
