### ISSUE TITLE
[BUG] Furniture replicating itself

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1748]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

When entering my warehouse interior, some decoration items are replicating themselves +1 instance every time you enter the building. It appears so far to be the TV and the swingable doors. This is causing severe performance degradation until the point of crashing the client.

Not sure what is triggering this exactly, or if it can be avoided, because one of the doors doesn't do it, while the one right next to it does, but they're the same object. Not seeing any feedback about issues in the logs either.

### Steps to Reproduce the Bug

1: decorate warehouse with swinging glass doors
2: leave house and come back inside 5 times
3: notice severe fps loss

### Expected Behavior

1 door or TV = 1 door or TV

### Screenshots/Videos

Can be provided upon request

**Comment by LitrlyD3ad** [comment]
My quick fix for this one was to delete the prop giving issues and put it back down. Ive found this issue happens when you place a object and buy it but move it after to another location, the script gets confused and puts the item back at the original location. So deleting it and putting it back down is what ive found to fix this.

**Comment by emeraldleo1982** [comment]
Will try that, I was just thinking maybe it's related to the fact that both the TV and doors in question are placed on the placeable wall tiles.
