### ISSUE TITLE
Oxy lab/trailer disappears when deployed

### ISSUE THREAD

**Issue by CyrusMancini** [ParadoxGamingRP/bugs-and-suggestions#2013]
### Your Discord Name

ntothej

### A clear and concise description of what the bug is

When trying to deploy the trailer, it disappears. A staff member tried to see if it fell through the map and it wasn't able to be located. I tried to deploy a trailer in two separate spots but it disappeared in both spots.

### Steps to Reproduce the Bug

1. Purchase a trailer
2. Bring it to the desired spot
3. Unhitch trailer
4. Deploy through 3rd eye option
5. (Poof)

### Expected Behavior

That it does not poof.

### Screenshots/Videos

N/A. 

### Log File

[CitizenFX_log_2023-12-22T214850.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13757206/CitizenFX_log_2023-12-22T214850.log)

**Comment by kingtortle** [comment]
I had the same thing happen but the lab was actually found and the door was unlocked until I relocked it and left the area and it disappeared again. It came back where it was deployed.

**Comment by tommytwoshotty** [comment]
To add to the above since this is a already opened report.
Mama coots oxy trailer was missing when i flew in. when checking my f8 i had this error message  attached is also my logs for when i flew in and the trailer was missing. I relogged at my house to see if i was to close. still got the same error
![FiveM_b2944_GTAProcess_g0lc61Lo1m](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/92126060/d5e92cda-8fa5-415a-97f5-e037c609f3aa)
[CitizenFX_log_2023-12-30T014320.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13796807/CitizenFX_log_2023-12-30T014320.log)
