### ISSUE TITLE
[ENHANCEMENT] Braking when stall

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2085]
KevStax

**Describe the annoyance**
when I stall at 100+mph I'm basically screwed as I watch my car drift into a wall.
**To Reproduce**
[Steps to reproduce the annoyance]
1.  stall
2.  be unable to brake
3. 

**Requested behavior**
when I stall I should be able to use my vehicle brakes to stop myself.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Kromlec** [comment]
Your handbrake works during the stall.

**Comment by kevstax** [comment]
right, but that doesn't really help when u stall out at 100+. if a car turns off the brakes should still be able to function properly.

**Comment by emeraldleo1982** [comment]
> Your handbrake works during the stall.

Does it? Cause I swear it never works on the Roxanne when I inevitably stall it. On the Roxanne note, it's especially dangerous when stalling at speed because of how it free coasts with no engine brake. Also there's the fact that we're required to slow down to 15mph before we can go again, so the engine restarts, but then we have to brake, before we can go.. just feels clunky.

But overall it doesn't make sense for the brakes to not work at all during a stall, no real car works this way because it would get people killed. Maybe 50% brakes when the car stalls would be a good compromise to simulate the brake booster loss when the ECU shuts off, if it's even possible to do?
