### ISSUE TITLE
[ENHANCEMENT] Cop Stamina/Speed

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#2094]
**Your Discord Name**
davefromsunderland

**Describe the annoyance**
cops hold the record for the fastest time in a 1000m sprint

**To Reproduce**
[Steps to reproduce the annoyance]
1. Be a cop 
2. Run

**Requested behavior**
make them either have slightly higher stamina or completely remove it. 

**Screenshots**

**Additional context**
I understand that this was added when the drug/food/water/whatever you might call it meta was a thing but it kinda died out and very little people use drugs and such nowadays anyway. When you are a cop you can catch up to crazy quick even with a big distance. I use a stupid run style that makes me run slower but I can still keep up very easily. When other cops are on foot pursuits with me they leave me in the dust because they run 2x the speed I do. Crims stand no chance in foot chases against the current state of cops.

**Comment by emeraldleo1982** [comment]
It was originally meant to increase the sales/use of drugs because everybody was just buying buff foods instead and the cop buff was so they wouldn't have to take drugs to compete. I personally have forgotten that drugs even exist as a crim. IMO, bring back food buff meta if the druggies aren't pushin' the stuff. I can't really blame the pushers though, not many want to buy the drugs either for character based reasons or the fact that the drugs don't really give you a noticeable advantage for the cost (feels more like paying for equal footing with the cops except your vision gets messed up) , then you get caught with drug charges as well.

But we have to remember that when food buffs were meta, everybody used them, cop and crim alike so it just balanced out for everybody to be equal unless somebody forgot to bring their snack-packs.

If we're thinking in terms of reality, cops should have higher stamina because of training and what not, but they're also carrying lots of heavy gear so often run slower than a wirey criminal fighting for his life all jacked up on adrenaline, which they generally make up for by utilizing their advantages; Teamwork, helicopter, dogs, etc.
