### ISSUE TITLE
[BUG] Store safes gets you stuck in place

### ISSUE THREAD

**Issue by Flawlessdx** [ParadoxGamingRP/bugs-and-suggestions#743]
### Your Discord Name

flowless#8302

### A clear and concise description of what the bug is

When you rob a store and gets the sticky note with the code and go back to the safe and put it in you get stuck in place and has do do a hard nap to be able to move agien and you dont the get stuff from the safe.

### Steps to Reproduce the Bug

1. Store robbery
2. Getting the code to safe
3. put in the code
4. Get stuck
5. Take a hard nap to reset

### Expected Behavior

What i expect to happen is to be able to go in to the safes agien without getting stuck in place and has to logout and lose the store

### Screenshots/Videos

Dont have any

**Comment by madsskyy** [comment]
do you know what store this was at?

**Comment by Flawlessdx** [comment]
Up in paleto bot the one close to the mechanic but the other one on the highway if that makes sence

**Comment by MilesMarvin** [comment]
So... I just experienced this last night, also at Paleto! The one near the gas station. Same thing, got the codes, put em in the safe, & next thing I know I'm glued to the floor. & had to take a nap!

Below I've added two logs, since I'm not too sure in which it occurred... 

[CitizenFX_log_2022-09-11T102833.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9542548/CitizenFX_log_2022-09-11T102833.log)
[CitizenFX_log_2022-09-10T164428.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9542549/CitizenFX_log_2022-09-10T164428.log)
