### ISSUE TITLE
[BUG] Bank Trucks being Scuffed

### ISSUE THREAD

**Issue by xaroht** [ParadoxGamingRP/bugs-and-suggestions#796]
### Your Discord Name

thørax#0098

### A clear and concise description of what the bug is

Bank Trucks Not Spawning In when Traffic is Heard.

### Steps to Reproduce the Bug

1. Scan for Truck
2. Get Traffic Heard
3. Realize that bank truck has not spawned and is scuffed
4. probably cry.

### Expected Behavior

1. Scan for Truck
2. Get Traffic Heard
3. Truck go boom
4. probably not cry

### Screenshots/Videos

https://i.imgur.com/O8S4OQX.png

### Extra Notes (Optional)

i didnt grab my logs and my medal wasnt working but we checked all the way through Route 68 and it was nowhere. hopefully other people are able to grab logs if this keeps happening.

**Comment by brittain1** [comment]
Your Discord Name
brittain#5713

A clear and concise description of what the bug is
Bank Trucks guards not being in the truck when hitting or being under the map

Steps to Reproduce the Bug
Scan for Truck
Get Traffic Heard
Find bank truck, see no guards are in it. get shot from under the floor
Sob yourself to sleep
Expected Behavior
Scan for Truck
Get Traffic Heard
Truck go boom with guards inside
Be happy boy
Screenshots/Videos

Extra Notes (Optional)


Log File
No response

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by xXJamieXx** [comment]
Closing stale issue due to no response.
