### ISSUE TITLE
[BUG] MDT Warrants

### ISSUE THREAD

**Issue by Supremekush** [ParadoxGamingRP/bugs-and-suggestions#978]
### Your Discord Name

Supremekush#5986

### A clear and concise description of what the bug is

I believe I have found a coding error within the MDT which causes the warrant to not be marked as processed after you save them as being marked processed and guilty and unselecting the warrant. It seems to only happen to the ones at are done close to the server restarts. This has only happened twice so as well as pouting in a bug report I'm going to make sure that it is not a human error as well but it seems to be more on the MDT side. I do know for sure it is an intermittent issue so getting it to reproduce is hard. 

that

### Steps to Reproduce the Bug

Put in warrant 
Survey warrant 
The warrant comes back up next restart {sometimes}

### Expected Behavior

Warrant gets removed from the dashboard when served 

### Screenshots/Videos

None

**Comment by xXJamieXx** [comment]
I need more info on this because it updates the database as soon as you save the report. If it failed to update the database then re-opening the report again (open a different one and then re-open the current one) would show the warrant active again. I can't think of any reason why it would appear again after a restart but not before. There is no delay on the update so I would appreciate some more testing and info on this because the current theory doesn't make sense.

**Comment by xXJamieXx** [comment]
> 

@Supremekush
